name: Deployment job

on: 
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: SetUp NodeJS version
            uses: actions/setup-node@v4
            with:
                node-version: 18

          - name: Cache NPM dependencies
            uses: actions/cache@v4
            with: 
                path: node_modules
                key: ${{runner.os}}-node_modules-${{hashFiles('package-lock.json')}}

          - name: Install dependencies
            run: npm install

          - name: Unit testing
            id: node-js-testing-setup
            run: npm test

          - name: Archive test result
            if: always()
            uses: actions/upload-artifact@v4
            with:
             name: Manuscript
             path: test-results.xml

    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: SetUp NodeJS version
            uses: actions/setup-node@v4
            with:
                node-version: 18

          - name: Cache NPM dependencies
            uses: actions/cache@v4
            with: 
                path: node_modules
                key: ${{runner.os}}-node_modules-${{hashFiles('package-lock.json')}}

          - name: Install dependencies
            run: npm install

          - name: Check code coverage
            run: npm run coverage
            continue-on-error: true

          - name: Archive coverage result
            if: always()
            uses: actions/upload-artifact@v4
            with:
             name: Coverage-result
             path: coverage
             retention-days: 5

    docker:
        needs: [build, coverage]
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: Dockerhub login
            uses: docker/login-action@v3
            with:
                username: ${{vars.DOCKER_USERNAME}}
                password: ${{secrets.DOCKER_PASSWORD}}

          - name: Docker Build
            uses: docker/build-push-action@v6
            with:
              context: .
              tags: ${{vars.DOCKER_USERNAME}}/node-web-app:${{github.sha}}
              
          - name: Run Docker Container
            run: |
             docker run -d --name node-web-app -p 3000:3000 ${{vars.DOCKER_USERNAME}}/node-web-app:${{github.sha}}

             echo Testing local app endpoint...
             wget -q -O - 127.0.0.1:3000 | grep "Hello"


