name: Deployment job

on: 
    push:
      branches:
        - main
        - 'feature/*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: SetUp NodeJS version
            uses: actions/setup-node@v4
            with:
                node-version: 18

          - name: Cache NPM dependencies
            uses: actions/cache@v4
            with: 
                path: node_modules
                key: ${{runner.os}}-node_modules-${{hashFiles('package-lock.json')}}

          - name: Install dependencies
            run: npm install

          - name: Unit testing
            id: node-js-testing-setup
            run: npm test

          - name: Archive test result
            if: always()
            uses: actions/upload-artifact@v4
            with:
             name: Manuscript
             path: test-results.xml

    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4

          - name: SetUp NodeJS version
            uses: actions/setup-node@v4
            with:
                node-version: 18

          - name: Cache NPM dependencies
            uses: actions/cache@v4
            with: 
                path: node_modules
                key: ${{runner.os}}-node_modules-${{hashFiles('package-lock.json')}}

          - name: Install dependencies
            run: npm install

          - name: Check code coverage
            run: npm run coverage
            continue-on-error: true

          - name: Archive coverage result
            if: always()
            uses: actions/upload-artifact@v4
            with:
             name: Coverage-result
             path: coverage
             retention-days: 5

    dev-docker:
        if: contains(github.ref, 'feature/')
        needs: [build, coverage]
        uses: ./.github/workflows/reuse-deployment.yml
        with:
          image-name: ${{ vars.DOCKER_USERNAME }}/node-web-app
          image-tag: v2
        secrets:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}

    prod-docker:
        if: github.ref == 'refs/heads/main'
        needs: [build, coverage]
        uses: ./.github/workflows/reuse-deployment.yml
        with:
          image-name: ${{ vars.DOCKER_USERNAME }}/node-web-app
          image-tag: v2
        secrets:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
